package cn.myflycat.mat.client.gui;

import cn.myflycat.mat.editor.ActionStep;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

public final class ScriptCodegen {
    private static final DateTimeFormatter FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());

    private ScriptCodegen() {}

    public static String generate(String scriptName, List<ActionStep> steps) {
        StringBuilder sb = new StringBuilder(4096);
        sb.append("// ").append(scriptName).append(".js\n");
        sb.append("// Generated by MAT Script Builder on ")
                .append(FMT.format(Instant.now())).append("\n");
        sb.append("// ").append(steps.size()).append(" steps\n\n");

        for (int i = 0; i < steps.size(); i++) {
            ActionStep step = steps.get(i);
            sb.append(step.toJavaScript()).append("\n");
            if (i < steps.size() - 1) {
                sb.append("\n");
            }
        }

        return sb.toString();
    }
}
