package cn.myflycat.mat.client.recorder;

import cn.myflycat.mat.recorder.ActionRecord;
import cn.myflycat.mat.recorder.ActionType;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

final class CodeGenerator {
    private static final DateTimeFormatter FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());

    private CodeGenerator() {}

    static String generate(List<ActionRecord> records, long startTime) {
        StringBuilder sb = new StringBuilder(4096);
        sb.append("// Generated by MAT Recorder on ")
                .append(FMT.format(Instant.ofEpochMilli(startTime)))
                .append("\n// ").append(records.size()).append(" actions captured\n\n");

        if (records.isEmpty()) return sb.toString();
        long prevTs = records.get(0).timestamp();
        for (ActionRecord record : records) {
            long delta = record.timestamp() - prevTs;
            if (delta > 50) {
                sb.append("mat.sleep(").append(delta).append(");\n");
            }
            prevTs = record.timestamp();
            emitAction(sb, record);
        }

        return sb.toString();
    }

    private static void emitAction(StringBuilder sb, ActionRecord r) {
        switch (r.type()) {
            case BREAK_BLOCK -> emitBreakBlock(sb, r);
            case PLACE_BLOCK -> emitPlaceBlock(sb, r);
            case USE_ITEM -> emitUseItem(sb, r);
            case ATTACK_ENTITY -> emitAttackEntity(sb, r);
            case INTERACT_ENTITY -> emitInteractEntity(sb, r);
            case MOVE -> emitMove(sb, r);
            case CHAT -> emitChat(sb, r);
        }
    }

    private static void emitBreakBlock(StringBuilder sb, ActionRecord r) {
        int x = r.param("x", 0);
        int y = r.param("y", 0);
        int z = r.param("z", 0);
        String block = r.param("block", "?");
        sb.append("// break ").append(block).append(" at (").append(x).append(", ")
                .append(y).append(", ").append(z).append(")\n");
        sb.append("// TODO: add block-breaking logic here\n");
    }

    private static void emitPlaceBlock(StringBuilder sb, ActionRecord r) {
        int x = r.param("x", 0);
        int y = r.param("y", 0);
        int z = r.param("z", 0);
        String block = r.param("block", "?");
        sb.append("// place ").append(block).append(" at (").append(x).append(", ")
                .append(y).append(", ").append(z).append(")\n");
        sb.append("// TODO: add block-placing logic here\n");
    }

    private static void emitUseItem(StringBuilder sb, ActionRecord r) {
        String hand = r.param("hand", "main_hand");
        String item = r.param("item", "?");
        sb.append("// used ").append(hand).append(": ").append(item).append("\n");
        sb.append("// TODO: add item-use logic here\n");
    }

    private static void emitAttackEntity(StringBuilder sb, ActionRecord r) {
        String entity = r.param("entity", "?");
        sb.append("// attack entity: ").append(entity).append("\n");
        sb.append("// TODO: add entity-attack logic here\n");
    }

    private static void emitInteractEntity(StringBuilder sb, ActionRecord r) {
        String entity = r.param("entity", "?");
        String hand = r.param("hand", "main_hand");
        sb.append("// interact with ").append(entity).append(" (").append(hand).append(")\n");
        sb.append("// TODO: add entity-interact logic here\n");
    }

    private static void emitMove(StringBuilder sb, ActionRecord r) {
        double x = r.param("x", 0.0);
        double y = r.param("y", 0.0);
        double z = r.param("z", 0.0);
        double yaw = r.param("yaw", 0.0);
        double pitch = r.param("pitch", 0.0);
        int bx = (int) Math.floor(x);
        int by = (int) Math.floor(y);
        int bz = (int) Math.floor(z);
        sb.append("// move to (").append(f(x)).append(", ").append(f(y)).append(", ").append(f(z))
                .append(") yaw=").append(f(yaw)).append(" pitch=").append(f(pitch)).append("\n");
        sb.append("mat.baritone.gotoBlock(").append(bx).append(", ").append(by).append(", ")
                .append(bz).append(");\n");
    }

    private static void emitChat(StringBuilder sb, ActionRecord r) {
        String msg = r.param("message", "");
        sb.append("mat.chat.send(").append(quote(msg)).append(");\n");
    }

    private static String f(double v) {
        if (v == Math.floor(v) && !Double.isInfinite(v)) {
            return String.valueOf((int) v);
        }
        return String.format("%.1f", v);
    }

    private static String quote(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r") + "\"";
    }
}
